// Sync CV data from the public Google Doc into user-data/data.js.
// Run: node scripts/sync-cv.mjs
// The parser keys on ALL-CAPS section headers (WORK EXPERIENCE / PROJECTS /
// EDUCATION / SKILLS) and "Title<2+ spaces or tab>Date" heading lines.
// If the doc format changes in a way the parser can't handle, the script
// aborts without writing, so the site keeps its last good data.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DOC_ID = "1IWPNyDfCLuRszsdUY09tJYt3xaivlXK0xBblbmBd8Co";
const URL = `https://docs.google.com/document/d/${DOC_ID}/export?format=txt`;
const SECTIONS = ["WORK EXPERIENCE", "PROJECTS", "EDUCATION", "SKILLS"];

const res = await fetch(URL, { redirect: "follow" });
if (!res.ok) fail(`Doc fetch failed: HTTP ${res.status}`);
const raw = (await res.text()).replace(/^﻿/, "").replace(/\r\n/g, "\n");

// Split into named sections
const lines = raw.split("\n");
const sections = {};
let current = null;
for (const line of lines) {
  const t = line.trim();
  if (SECTIONS.includes(t)) { current = t; sections[current] = []; continue; }
  if (current) sections[current].push(line);
}
for (const s of ["WORK EXPERIENCE", "EDUCATION", "SKILLS"]) {
  if (!sections[s] || !sections[s].some((l) => l.trim())) fail(`Section missing/empty: ${s}`);
}

// A heading line is "Title<TAB or 2+ spaces>DateRange"
const HEADING = /^(\S.*?)(?:\t+| {2,})(\S.*(?:\d{4}|Now|Present).*)$/;

function parseEntries(sectionLines) {
  const entries = [];
  let entry = null;
  for (const line of sectionLines) {
    if (!line.trim()) continue;
    const h = !/^\s/.test(line) && HEADING.exec(line.trimEnd());
    if (h) {
      entry = { title: h[1].trim(), date: h[2].trim(), bullets: [], plain: [] };
      entries.push(entry);
      continue;
    }
    if (!entry) continue;
    const bullet = /^(\s*)\*\s+(.*)$/.exec(line);
    if (bullet) {
      const isSub = bullet[1].length > 0;
      const text = bullet[2].trim();
      if (isSub && entry.bullets.length) entry.bullets[entry.bullets.length - 1].subs.push(text);
      else entry.bullets.push({ text, subs: [] });
    } else {
      entry.plain.push(line.trim());
    }
  }
  return entries;
}

const work = parseEntries(sections["WORK EXPERIENCE"]).map((e) => {
  // Continuation lines after bullets belong to the last bullet
  if (e.plain.length && e.bullets.length) {
    const last = e.bullets[e.bullets.length - 1];
    last.text = (last.text + " " + e.plain.join(" ")).trim();
    e.plain = [];
  }
  const at = e.title.split(/\s+at\s+/);
  const role = at.length > 1 ? at[0].trim() : "";
  const company = at.length > 1 ? at.slice(1).join(" at ").trim() : e.title;
  return {
    company,
    role,
    date: e.date,
    initial: company.charAt(0).toUpperCase(),
    bullets: e.bullets,
  };
});

const projects = parseEntries(sections["PROJECTS"] || []).map((e) => ({
  name: e.title,
  date: e.date,
  bullets: e.bullets,
}));

const education = parseEntries(sections["EDUCATION"]).map((e) => ({
  school: e.title,
  degree: e.plain[0] || "",
  date: e.date,
  initial: e.title.charAt(0).toUpperCase(),
  bullets: e.plain.slice(1).map((text) => ({ text, subs: [] })),
}));

const skills = [];
for (const line of sections["SKILLS"]) {
  const m = /^([^:]{1,60}):\s*(.+)$/.exec(line.trim());
  if (m) skills.push({ category: m[1].trim(), items: splitItems(m[2]) });
}

// Sanity gates — abort rather than write bad data
if (work.length < 1) fail("Parsed 0 work entries");
if (education.length < 1) fail("Parsed 0 education entries");
if (skills.length < 2) fail(`Parsed only ${skills.length} skill categories`);
if (work.some((w) => !w.date)) fail("Work entry without date");

const data = { generatedAt: new Date().toISOString(), work, projects, education, skills };
const out = "// AUTO-GENERATED by scripts/sync-cv.mjs — do not edit by hand.\n" +
  "window.CV_DATA = " + JSON.stringify(data, null, 2) + ";\n";

const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "user-data");
mkdirSync(dir, { recursive: true });
writeFileSync(join(dir, "data.js"), out);
console.log(`OK: ${work.length} work, ${education.length} education, ${skills.length} skill categories, ${projects.length} projects`);

// Split on commas, but not inside parentheses ("MS Office (Word, Excel)")
function splitItems(s) {
  const items = [];
  let buf = "", depth = 0;
  for (const ch of s) {
    if (ch === "(") depth++;
    else if (ch === ")") depth = Math.max(0, depth - 1);
    if (ch === "," && depth === 0) { items.push(buf.trim()); buf = ""; }
    else buf += ch;
  }
  if (buf.trim()) items.push(buf.trim());
  return items.filter(Boolean);
}

function fail(msg) {
  console.error("ABORT (no write): " + msg);
  process.exit(1);
}
