// AUTO-GENERATED by scripts/sync-cv.mjs — do not edit by hand.
window.CV_DATA = {
  "generatedAt": "2026-07-12T16:51:42.945Z",
  "work": [
    {
      "company": "Avicenna Ambulance",
      "role": "Automation Engineer",
      "date": "May 2026 - Now",
      "initial": "A",
      "bullets": [
        {
          "text": "Designed workflow using n8n in to automate: streamlining the company process and reducing cost.",
          "subs": [
            "SMS notification",
            "GDPR-compliant medical data OCR",
            "Error detection in data entry",
            "KPIs measurement",
            "Petrol station price optimization"
          ]
        }
      ]
    },
    {
      "company": "Freelancer",
      "role": "",
      "date": "Jan 2023 - Mar 2026",
      "initial": "F",
      "bullets": [
        {
          "text": "Designed a Telegram chatbot in Python integrating LLM with Tavily API, enabling news summarization and financial analysis, deployed on Railway.",
          "subs": []
        },
        {
          "text": "Maintained and improved a content management system (CMS) for public facility digital platforms by collaborating in weekly sprints in a Scrum-based Agile team.Development of an AI-driven content creation pipeline for dynamic video generation with automated workflows for continuous output. Built with Python, LangChain, and OpenAI API for content generation, integrated with video synthesis tools such as RunwayML and FFmpeg. Deployed on AWS Lambda for scalable, cost-effective execution with automated scheduling via Apache Airflow.",
          "subs": []
        }
      ]
    },
    {
      "company": "Ministry of Communication and Digital Affairs",
      "role": "Web Developer Intern",
      "date": "Jul 2022 - Dec 2022",
      "initial": "M",
      "bullets": [
        {
          "text": "Maintained and improved a content management system (CMS) for public facility digital platforms by collaborating in weekly sprints in a Scrum-based Agile team.",
          "subs": []
        }
      ]
    }
  ],
  "projects": [
    {
      "name": "Tourism App with Personalized Travel Recommendations",
      "date": "May 2026",
      "bullets": [
        {
          "text": "Developed a web app to promote tourism in Indonesia. Implemented using Flutter Web and Firebase (Firestore, Authentication, Cloud Functions). Integrated the Google Maps Platform and Gemini API to provide personalized travel recommendations. Deployed to Google Cloud Run with CI/CD via Cloud Build.",
          "subs": []
        }
      ]
    },
    {
      "name": "AI Agent & Workflow Automation",
      "date": "Mar 2026",
      "bullets": [
        {
          "text": "Built a personal assistant workflow in n8n integrating Email, WhatsApp and Airtable, enabling natural language commands via LLM to create, edit, and manage schedule and budget data across multi-step pipelines.",
          "subs": []
        }
      ]
    },
    {
      "name": "Retrieval Augmented Generation",
      "date": "Jun 2025",
      "bullets": [
        {
          "text": "Implemented a RAG pipeline using LLM and LangChain to build a CV-based QA chatbot with contextual retrieval and response generation, deployed on Cloudflare.",
          "subs": []
        }
      ]
    }
  ],
  "education": [
    {
      "school": "Dresden University of Technology, Germany",
      "degree": "Currently pursuing Master in Computer Science",
      "date": "Apr 2026 - Present",
      "initial": "D",
      "bullets": []
    },
    {
      "school": "Brawijaya University, Indonesia",
      "degree": "Graduated with Bachelor in Informatics",
      "date": "Aug 2019 - Jan 2023",
      "initial": "B",
      "bullets": [
        {
          "text": "Thesis: Generative Image for Data Augmentation",
          "subs": []
        }
      ]
    }
  ],
  "skills": [
    {
      "category": "Programming Language",
      "items": [
        "Python",
        "HTML",
        "CSS",
        "Javascript"
      ]
    },
    {
      "category": "Library",
      "items": [
        "NumPy",
        "pandas",
        "scikit-learn",
        "TensorFlow",
        "Keras",
        "PyTorch",
        "LangChain"
      ]
    },
    {
      "category": "Database",
      "items": [
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "SQL Server"
      ]
    },
    {
      "category": "Other",
      "items": [
        "MS Office (Word, Excel, PowerPoint)",
        "AI Studio",
        "n8n",
        "Git",
        "Docker"
      ]
    },
    {
      "category": "Language",
      "items": [
        "English (C1)",
        "German (B2)",
        "Indonesian (Native)"
      ]
    }
  ]
};
